Desktop/OnField_master/config/routes.rb
Rails.application.routes.draw do

  root 'posts#calender' 

  # devise
  devise_for :users, :controllers => {sessions: 'users/sessions', registrations: 'users/registrations'}
  resources :users

  devise_scope :user do
    get 'users/solo_users' => 'users/registrations#solo_users'
  end

  def devise_scope(scope)
    constraint = lambda do |request|
      request.env["devise.mapping"] = Devise.mappings[scope]
      true
    end

    constraints(constraint) do
      yield
    end

  end

  # 投稿
  get 'posts/comp'
  get 'posts/back'
  get 'posts/search'
  get 'posts/search_clear'
  get 'posts/details/:id', to: 'posts#details'
  get 'posts/calender/:start_time', to: 'posts#show'
  get 'posts/show_search'
  resources :posts

  resources :posts do
    member do
      get 'take'
      get 'cancel'
    end
  end
  
  # チャット
  resources :rooms

  # 個人情報
  get 'solo_users/comp'
  get 'solo_users/back'
  resources :solo_users

  # チーム情報
  get 'teams/comp'
  get 'teams/back'
  resources :teams

  # コメント機能
  resources :posts do
    resources :comments, only: [:create]
  end

  # 通知機能
  resources :notifications, only: :index

end

Desktop/OnField_master/app/models/solo_user.rb
class SoloUser < ApplicationRecord
  validates :name, presence: true

  has_many :post_takers, foreign_key: "taker_id", dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  belongs_to :user

  mount_uploader :user_image, UserImageUploader

  #確認画面に飛ばすため
  validates_acceptance_of :confirming
  after_validation :check_confirming

  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  # 自分からの通知
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  # 相手からの通知
  
  def check_confirming
    errors.delete(:confirming)
    self.confirming = errors.empty? ? '1' : ''
  end

end

Desktop/OnField_master/app/controllers/solo_users_controller.rb
class SoloUsersController < ApplicationController
  before_action :authenticate_user!

    def index
      @solo_user = SoloUser.new(session[:solo_user])
      session.delete(:solo_user)
      render :new
    end

    def new
        @solo_user = SoloUser.new
    end

    def create
        @solo_user = SoloUser.new(solo_user_params)
        if @solo_user.save
          redirect_to solo_users_comp_path
        else
          session[:solo_user] = @solo_user
          render :new
        end
      end
    
    def back
        @solo_user = SoloUser.new(session[:solo_user])
        session.delete(:solo_user)
        render :new
    end

    def show
      @solo_user = SoloUser.find_by(user_id: params[:id])
    end

    def edit
      @solo_user = SoloUser.find(params[:id])
    end

    def update
      @solo_user = SoloUser.find(params[:id])
       
      #編集しようとしてるユーザーがログインユーザーとイコールかをチェック
      if current_user == @solo_user
       
        if @solo_user.update!(solo_user_params)
          flash[:success] = 'ユーザー情報を編集しました。'
          render :edit
        else
          flash.now[:danger] = 'ユーザー情報の編集に失敗しました。'
          render :edit
        end
       
      else
          redirect_to root_path
      end
      end
    
    private

    def solo_user_params
        params.require(:solo_user).permit(:user_id, :name, :contents, :sports, :user_image, :category, :confirming, :place, :level).merge(user_id:current_user.id)
    end

end

Desktop/OnField_master/app/helpers/solo_users_helper.rb
module SoloUsersHelper
end

Desktop/OnField_master/app/views/solo_users/comp.html.erb
<div class="user-comp-outer">
    <div class="user-comp-inner">
        <h1>登録が完了しました。</h1>
        <div class="user-comp-contents">
        <span style="text-decoration: underline"><p><%= link_to "トップページ", root_path %></p></span>
        <span style="text-decoration: underline"><p><%= link_to "ログアウト", destroy_user_session_path, method: "delete" %></p></span>
        </div>
        </div>
</div>

Desktop/OnField_master/app/views/solo_users/edit.html.erb
<%= form_with(model: @solo_user, local: true) do |f| %>
    <div>
      <%= f.label :チーム名又は個人名（ニックネーム可） %>
      <%= f.text_field :name %><br>

      <%= f.label :カテゴリ又はレベルの目安 %>
      <%= f.text_field :level %><br>

      <%= f.label :主な活動場所 %>
      <%= f.text_field :place %><br>

      <%= link_to 'キャンセル', edit_solo_user_path %>
      <%= f.submit "保存" %>
    </div>
  <% end %>

Desktop/OnField_master/app/views/solo_users/new.html.erb
<div class="user-new-outer">
  <div class="user-new-inner">
    <div class="user-new-top">
      <div class="user-new-image">
        <img src="/assets/OnField-logo.png" width="128" height="100">
      </div>
        <p><font size="5" color="#3cb371" face="">無料新規会員登録</font></p>
    </div>

    <div class="user-new-outer-box">
      <div class="user-new-inner-box">
        <div class="user-new-label">

        <% if @solo_user.confirming != '1' %> 
          <%= form_with(model: @solo_user, local: true) do |f| %>
            <div>
              <div class="name">
                <%= f.label :ニックネームまたはチーム名 %><br>
                <%= f.text_field :name %><br>
              </div>

              <%= f.label :登録種別 %><br>
              <div class="people">
              <div class="team">
                <%= f.radio_button :category, "チーム" %> チーム
              </div>
              <div class="solo">
                <%= f.radio_button :category, "個人" %>個人<br>
              </div>
              </div>

              <%= f.label :登録種別 %><br>
              <div class="sports">
              <div class="football">
                <%= f.radio_button :sports, "サッカー" %> サッカー
              </div>
              <div class="futsal">
                <%= f.radio_button :sports, "フットサル" %>フットサル<br>
              </div>
              </div>

              <%= f.hidden_field :confirming %>
            </div>
            <div class="user-new-bottom">
              <%= f.submit "確認画面へ", class: "btn btn-success login-btn" %>
            </div>
            </div>
          <% end %>

        <% else %>
        <div class="user-confirm-label">

          <%= form_with(model: @solo_user, local: true) do |f| %>
            <div>
            <% if @solo_user.category == 'チーム' then %>
              <%= f.label :チーム名 %>
              <span style="text-decoration: underline"><%= @solo_user.name %><br></span>
            <% else %>
              <%= f.label :ニックネーム %>
              <span style="text-decoration: underline"><%= @solo_user.name %><br></span>
            <% end %>

              <%= f.label :登録種別 %>
              &ensp; &thinsp; &thinsp;
              <% if @solo_user.sports == 'チーム' then %> 
              <span style="text-decoration: underline">チーム</span>
              <% else %>
              <span style="text-decoration: underline">個人</span>
              <% end %><br>

              <%= f.label :スポーツ種別 %>
              <% if @solo_user.sports == 'サッカー' then %> 
              <span style="text-decoration: underline">サッカー</span>
              <% else %>
              <span style="text-decoration: underline">フットサル</span>
              <% end %><br>


              <%= f.hidden_field :name %>
              <%= f.hidden_field :category %>
              <%= f.hidden_field :sports %>
              <%= f.hidden_field :confirming %>
            </div>
            </div>


              <div class="user-confirm-bottom">
              <%= f.submit "会員登録", class: "btn btn-success login-btn" %><br>

          <% end %>
          <%= link_to "戻る", solo_users_back_path %>
        <% end %>
        </div>
        </div>
  </div>
</div>

Desktop/OnField_master/app/views/solo_users/show.html.erb
<h1>ユーザーマイページ</h1>
<%= image_tag @solo_user.user_image.url %>
<%= @solo_user.name %>　
<%= link_to 'プロフィール編集', edit_solo_user_path(current_solo.id) %>