Desktop/OnField_master/config/routes.rb
Rails.application.routes.draw do

  root 'posts#calender' 

  # devise
  devise_for :users, :controllers => {sessions: 'users/sessions', registrations: 'users/registrations'}
  resources :users

  devise_scope :user do
    get 'users/solo_users' => 'users/registrations#solo_users'
  end

  def devise_scope(scope)
    constraint = lambda do |request|
      request.env["devise.mapping"] = Devise.mappings[scope]
      true
    end

    constraints(constraint) do
      yield
    end

  end

  # 投稿
  get 'posts/comp'
  get 'posts/back'
  get 'posts/search'
  get 'posts/search_clear'
  get 'posts/details/:id', to: 'posts#details'
  get 'posts/calender/:start_time', to: 'posts#show'
  get 'posts/show_search'
  resources :posts

  resources :posts do
    member do
      get 'take'
      get 'cancel'
    end
  end
  
  # チャット
  resources :rooms

  # 個人情報
  get 'solo_users/comp'
  get 'solo_users/back'
  resources :solo_users

  # チーム情報
  get 'teams/comp'
  get 'teams/back'
  resources :teams

  # コメント機能
  resources :posts do
    resources :comments, only: [:create]
  end

  # 通知機能
  resources :notifications, only: :index

end

Desktop/OnField_master/app/models/notification.rb
class Notification < ApplicationRecord
    # 降順でデータを持ってくる
    default_scope -> { order(created_at: :desc) }

    belongs_to :post_taker, optional: true
    belongs_to :comment, optional: true
    belongs_to :message, optional: true
    belongs_to :post, optional: true

  
    belongs_to :visitor, class_name: 'SoloUser', foreign_key: 'visitor_id', optional: true
    belongs_to :visited, class_name: 'SoloUser', foreign_key: 'visited_id', optional: true
end

Desktop/OnField_master/app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

    def index
        @notifications = current_solo.passive_notifications.page(params[:page]).per(10)
        @notifications.where(checked: false).each do |notification|
        notification.update_attributes(checked: true)
        end
    end
    
end

Desktop/OnField_master/app/helpers/notifications_helper.rb
module NotificationsHelper
end

Desktop/OnField_master/app/views/notifications/_notification.html.erb
<% visitor = notification.visitor %>
<% visited = notification.visited %>
<% post = notification.post %>

<tr>
<div>
    <td><%= link_to solo_user_path(visitor) do %>
        <%= visitor.name %>
    <% end %>
    <% if notification.action == 'message' %>
        さんから
    <% else %>
        さんが
    <% end %>
    <% case notification.action %>
        <% when 'post_taker' then %>
        <%= link_to post.title, {controller: :posts,action: :details,id: post.id} %>に申込しました。</td>
        <td><%= notification.created_at.strftime("%m月%d日")  %></td>
        <% when 'message' then %>
        <%= link_to 'メッセージ', room_path(notification.room_id) %>が届きました。</td>
        <td><%= notification.created_at %></td>
        <% when 'comment' then %>
    <% if post.solo_user_id == visited.id %>
        <%= link_to "あなたの投稿", {controller: :posts,action: :details,id: post.id} %>
    <% else %>
        <% link_to post_path(notification.post) do %>
                <= notification.post.user.name + 'さんの投稿' %>
        <% end %>
    <% end %>
            にコメントしました。</td>
            <td><%= notification.created_at.strftime("%m月%d日") %></td>
    <% end %>
</div>
</tr>

Desktop/OnField_master/app/views/notifications/index.html 2.erb
<h1>通知一覧</h1>
<% notifications = @notifications.where.not(visitor_id: current_user.id) %>

    <% if notifications.exists? %>
        <%= render notifications %>
        <%= paginate notifications %>
    <% else %>
        <p>通知はありません</p>
    <% end %>

Desktop/OnField_master/app/views/notifications/index.html.erb
<article id="notification-list">
<section class="section-display-area">
  <div class="table-title-box">
  <h1 class="table-title">通知一覧</h1>
  </div>
  <% notifications = @notifications.where.not(visitor_id: current_user.id) %>
    <% if notifications.exists? %>
  <div class="notification-list-table-box">
    <table>
      <thead>
        <tr>
        <th width="80%">通知</th>
        <th width="20%">受信日</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <%= render notifications %>
      </tr>
     </tbody>
     </table>
   </div>
 </section>
    <% else %>
        <p>通知はありません</p>
    <% end %>
</article>

<div class="pagination">
<%= paginate notifications %>
</div>