Desktop/OnField_master/config/routes.rb
Rails.application.routes.draw do

  root 'posts#calender' 

  # devise
  devise_for :users, :controllers => {sessions: 'users/sessions', registrations: 'users/registrations'}
  resources :users

  devise_scope :user do
    get 'users/solo_users' => 'users/registrations#solo_users'
  end

  def devise_scope(scope)
    constraint = lambda do |request|
      request.env["devise.mapping"] = Devise.mappings[scope]
      true
    end

    constraints(constraint) do
      yield
    end

  end

  # 投稿
  get 'posts/comp'
  get 'posts/back'
  get 'posts/search'
  get 'posts/search_clear'
  get 'posts/details/:id', to: 'posts#details'
  get 'posts/calender/:start_time', to: 'posts#show'
  get 'posts/show_search'
  resources :posts

  resources :posts do
    member do
      get 'take'
      get 'cancel'
    end
  end
  
  # チャット
  resources :rooms

  # 個人情報
  get 'solo_users/comp'
  get 'solo_users/back'
  resources :solo_users

  # チーム情報
  get 'teams/comp'
  get 'teams/back'
  resources :teams

  # コメント機能
  resources :posts do
    resources :comments, only: [:create]
  end

  # 通知機能
  resources :notifications, only: :index

end

Desktop/OnField_master/app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>OnField</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
<%# Googleフォント %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Sawarabi+Gothic&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=DotGothic16&display=swap" rel="stylesheet">

<%# bootstrap %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </head>

  <body>
  <div id="wrapper">

  <%= javascript_pack_tag 'hello_vue' %>
  <%= stylesheet_pack_tag 'hello_vue'  %>

  <header id="header">
  
  <div class="table-side-line center-placement">
    <h1 class="side-line header-left">
      <img src="/assets/OnField-logo.png" width="128" height="100">
    </h1>
    <% if user_signed_in? %>
    <nav class="side-line header-right">
      <div class="header-right-top">
        <ul class="header-right-top-left">
          <li><%= link_to "ログイン", new_user_session_path %></li>
          <li><%= link_to "新規会員登録", root_path %></li>
        </ul>
        <ul class="header-right-top-right">
        <li><%= link_to "ログアウト", destroy_user_session_path, method: "delete" %></li>
          <li>
              <img src="/assets/configuration.jpg" width="20" height="20">
          </li>
        </ul>
      </div>
      
      <div class="header-right-bottom">
        <ul>
          <li><%= link_to "HOME", root_path %></li>
          <li><%= link_to "マイページ", solo_user_path(current_user.id), method: "get" %></li>
          <li><%= link_to "トーク", rooms_path %></li>
          <li><%= link_to "新規募集",new_post_path %></li>
          <li><%= link_to "通知", notifications_path %></li>
          <li><%= link_to "パスワード変更", edit_user_registration_path %></li>
        </ul>
      </div>
      
    </nav>
    <% else %>

    <nav class="side-line header-right">
      <div class="header-right-top">
        <ul class="header-right-top-left">
          <li><%= link_to "ログイン", new_user_session_path %></li>
          <li><%= link_to "新規会員登録", root_path %></li>
        </ul>
      </div>
      
      <div class="header-right-bottom">
        <ul>
          <li><%= link_to "TOP", root_path %></li>
          <li><%= link_to "ログイン", root_path %></li>
          <li><%= link_to "新規会員登録", root_path %></li>
        </ul>
      </div>
      
    </nav>

    <% end %>
  </div>
  
</header>

  <main>
    <% if flash[:notice] %>
      <div class="alert alert-info">
        <%= flash[:notice] %>
       </div>
    <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>
      <%= yield %>
  </main>

  <footer>
      <div class="link">
        <p>On Field (オンフィールド)</p>
        <ul>
          <li><%= link_to 'サービス概要', root_path, class:"Editlink" %></li>
          <li><%= link_to '利用規約・プライバシーポリシー', root_path, class:'Editlink' %></li>
          <li><%= link_to '広告掲載をご希望の方', root_path, class:'Editlink' %></li>
        </ul>
      </div>
    </div>
  </footer>
  </div>
  </body>

</html>