Desktop/OnField_master/config/routes.rb
Rails.application.routes.draw do

  root 'posts#calender' 

  # devise
  devise_for :users, :controllers => {sessions: 'users/sessions', registrations: 'users/registrations'}
  resources :users

  devise_scope :user do
    get 'users/solo_users' => 'users/registrations#solo_users'
  end

  def devise_scope(scope)
    constraint = lambda do |request|
      request.env["devise.mapping"] = Devise.mappings[scope]
      true
    end

    constraints(constraint) do
      yield
    end

  end

  # 投稿
  get 'posts/comp'
  get 'posts/back'
  get 'posts/search'
  get 'posts/search_clear'
  get 'posts/details/:id', to: 'posts#details'
  get 'posts/calender/:start_time', to: 'posts#show'
  get 'posts/show_search'
  resources :posts

  resources :posts do
    member do
      get 'take'
      get 'cancel'
    end
  end
  
  # チャット
  resources :rooms

  # 個人情報
  get 'solo_users/comp'
  get 'solo_users/back'
  resources :solo_users

  # チーム情報
  get 'teams/comp'
  get 'teams/back'
  resources :teams

  # コメント機能
  resources :posts do
    resources :comments, only: [:create]
  end

  # 通知機能
  resources :notifications, only: :index

end

Desktop/OnField_master/app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :start_time, presence: true
  validates :match_start, presence: true

  has_many :post_takers, dependent: :destroy
  has_many :takers, through: :post_takers, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :rooms, dependent: :destroy
  has_many :notifications, dependent: :destroy

  belongs_to :solo_user, optional: true
  belongs_to :user, optional: true

  mount_uploader :game_image, GameImageUploader

      #確認画面に飛ばすため
  validates_acceptance_of :confirming
  after_validation :check_confirming

  def check_confirming
    errors.delete(:confirming)
    self.confirming = errors.empty? ? '1' : ''
  end

  # ---------------申込通知---------------

  def create_notification_post_taker!(current_solo, visited_id)
    notification = current_solo.active_notifications.new(
    post_id: id,
    visited_id: visited_id,
    action: 'post_taker')

  notification.save if notification.valid?
  end

  # ---------------コメント通知---------------

  def create_notification_comment!(current_solo, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:solo_user_id).where(post_id: id).where.not(user_id: current_solo.id).distinct

    temp_ids.each do |temp_id|
      save_notification_comment!(current_solo, comment_id, temp_id['solo_user_id'])
    end

      save_notification_comment!(current_solo, comment_id, solo_user_id) if temp_ids.blank?
  end

  def save_notification_comment!(current_solo, comment_id, visited_id)
      # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_solo.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
      # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

  
end

Desktop/OnField_master/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:index,:new, :create, :back, :comp, :details]

  def index
    @events = Post.all
    
  end

  def new
    @event = Post.new
  end

  def show

    @date_time = params[:start_time].to_datetime
    if session[:event]  && session[:event] != nil

p session[:event]

      @events = session[:event].where(start_time: @date_time)
      @events.page(params[:page]).per(10)



      # @events = Array.new
      # session[:event].each do |e|
      #   if Post.find(e).start_time == @date_time
      #     event = Post.find(e)
      #     @events.push(event)
      #   end
      # end
      
    else
      @events= Post.where(start_time: @date_time).page(params[:page]).per(10)
    end
  end

  def show_search
    @date_time = params[:time].to_datetime
    @events = Post.where(start_time: @date_time).where("title LIKE ? OR place LIKE ? OR contributor LIKE ?", "%#{params[:keyword]}%", "%#{params[:keyword]}%", "%#{params[:keyword]}%").page(params[:page]).per(10)
    render :show
  end

  def create
    @event = Post.new(post_params)
    if @event.save
      redirect_to posts_comp_path
    else
      session[:post] = @event
      render :new
    end
  end

  def back
    @event = Post.new(session[:post])
    session.delete(:post)
    render :new
  end

  def calender
    @events = Post.all
    @area = Post.group(:area).pluck(:area).sort
    @match = Post.group(:match).pluck(:match).sort
    @sports = Post.group(:sports).pluck(:sports).sort
  end

  def search
    @events = Post.where("area LIKE ? AND match LIKE ? AND sports LIKE ?", "%#{params[:area]}%", "%#{params[:match]}%", "%#{params[:sports]}%")
    if @events == []
      p '🌟🌟🌟'
      @events = []
      session[:event] = @events
      @area = Post.group(:area).pluck(:area).sort
      @match = Post.group(:match).pluck(:match).sort
      @sports = Post.group(:sports).pluck(:sports).sort
    else
      session[:event] = @events
      @area = Post.group(:area).pluck(:area).sort
      @match = Post.group(:match).pluck(:match).sort
      @sports = Post.group(:sports).pluck(:sports).sort
    end
    render :calender
  end

  def search_clear
    if session[:event] != nil
      session[:event] = nil
      redirect_to root_path
    else
      redirect_to root_path
    end
  end

  def comp
  end

  def details
    set_post
    @event = Post.find_by(id:params[:id])
    @comments = @post.comments
    @comment = @post.comments.build
    @user = @post.solo_user
  end

  def take
    set_post
    PostTaker.create(post_id: @post.id, taker_id: current_user.id)
    Room.create!(post_id: @post.id, solo_user_id: current_user.id, partnar_id: @post.solo_user_id)
    @post.create_notification_post_taker!(current_solo, @post.solo_user_id)
    flash[:notice] = '申し込みが完了しました。'
    redirect_to action: "details"
  end

  def cancel
    set_post
    post_taker = PostTaker.find_by(post_id: @post.id, taker_id: current_user.id)
    room = Room.find_by(post_id: @post.id, solo_user_id: current_user.id)
    post_taker.destroy
    room.destroy
    flash[:notice] = 'キャンセルが完了しました。'
    redirect_to action: "details"
  end

  private

  def post_params
    params.require(:post).permit(:title, :start_time, :match_start, :area, :place, :match, :sports, :category,
                                 :game_contents, :solo_user_id, :confirming ).merge(solo_user_id: current_user.id, contributor: current_solo.name)
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

Desktop/OnField_master/app/helpers/posts_helper.rb
module PostsHelper
end

Desktop/OnField_master/app/views/posts/calender.html.erb
<div class='home-page'>
<div class="top-box">
  <%= image_tag 'field.jpg', class: "field-image" %>
    <div class="top-contents">
      <div class="onfield">
      <p>On Field（オンフィールド）とは</p>
      </div>
      <div class="content">
      <p>ー&ensp; On Fieldはサッカー・フットサルに特価した<b><u>完全無料のマッチングプラットフォーム</u></b>です。</p>
      <p>ー&ensp; チームでの活動では練習試合相手を募集、個人での活動では参加しづらい個サル仲間を募集できます。</p>
      <p>ー&ensp; カレンダー機能によって自分が活動したい日の募集をピンポイントに探すことができます。</p>
      </div>
    </div>
</div>

<div id='main'>

<%# カレンダー %>
      <div class='calender'>
        <%= month_calendar events: @events do |date, events| %>
          <div class='a'>
            <%= link_to date.day, {controller: :posts, action: :show, start_time: date }, :style=>"color:black" %>
          </div>
        <% end %>
      </div>

<%# 検索機能 %>
<div class="box1">
  <div class='sort'>
    <h3>絞り込み</h3></br>
    <%= form_tag(posts_search_path, method: "get") do %>
      <div class="select-tag">
        <%= select_tag :area, options_for_select(@area), include_blank: '選択してください', class: 'form-control' , required: true %></br>
        <%= select_tag :sports, options_for_select(@sports), include_blank: '選択してください', class: 'form-control' , required: true %></br>
        <%= select_tag :match, options_for_select(@match), include_blank: '選択してください', class: 'form-control' , required: true %></br>
        <%= submit_tag "絞り込み", class: 'btn btn-primary btn-block', style:"background-color:black" %>
      </div>
    <% end %>
    <%= link_to "絞り込み解除", posts_search_clear_path, style:"color:black" %>
  </div>
</div>

</div>
</div>

Desktop/OnField_master/app/views/posts/comp.html.erb
<h1>募集しました。</h1>

<%= link_to '引続き募集を行う', new_post_path %><br>
<%= link_to 'トップページに戻る', root_path %>

Desktop/OnField_master/app/views/posts/details.html.erb
<h1>募集詳細</h1>
<%= @event.title %></br>
<%= @event.start_time.strftime("%Y-%m-%d") %></br>
<%= @event.match_start.strftime("%H:%M:%S") %></br>
<%= @event.area %></br>
<%= @event.match %>

<div class="comment-wrapper border-top　mb-10">
  <p class="mt-5">コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <% unless c.solo_user.blank? %>
        <a href="<%= solo_user_path(c.solo_user_id) %>"><%= image_tag c.solo_user.user_image.to_s,
          class:"rounded-circle icon_image mr-3 mb-3"%></a>
        <% end %>
      <%= c.solo_user.name unless c.solo_user.blank? %>
      <br />
      <%= c.content %>
    </div>
    <br />
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@post, @comment], local: true) do |f| %>
      <%= f.text_area :content, class: "form-control", rows: 5 %>
      <%= button_tag type: "submit", class: "btn btn-success float-right mt-1" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>

</div>

<% if @user.id != current_user.id %>
<% if @post.taker_ids.include?(current_user.id) %>
<%= link_to '申込をキャンセルする', cancel_post_path(@post.id), data: { confirm: "こちらの投稿の申し込みをキャンセルしますか？" } %>
<% else %>
<%= link_to '申し込む', take_post_path(@post.id), data: { confirm: "こちらの投稿に申し込みますか？" } %>
<% end %>
<% end %>

Desktop/OnField_master/app/views/posts/index.html.erb
<% @events.each do |event| %>
  <%= link_to event.title, {controller: :posts,action: :details,id: event.id} %>
  <% if event.game_image? %>
  <%= image_tag event.game_image.url %><br>
  <% else %>
  <%= image_tag '/assets/default_post.jpg' %><br>
  <% end %>
<% end %>

Desktop/OnField_master/app/views/posts/new.html.erb
<% if @event.confirming != '1' %> 
    <%= form_for @event, multipart: true, local: true do |f| %>
        <div>
            <div>
                <%= f.select :sports, [["サッカー", "サッカー"], ["フットサル", "フットサル"]], placeholder: "サッカー" %>
            </div>
            <div>
                <%= f.select :match, [["練習試合", "練習試合"], ["本番試合", "本番試合"]], placeholder: "練習試合" %>
            </div>
            <div>
                <%= f.label :"募集タイトルを入力" %></br>
                <%= f.text_area :title %>
            </div>

            <div>
                <%= f.label :"試合日を選択" %></br>
                <%= f.date_select :start_time, {include_blank: true, use_month_numbers: true, start_year:Time.now.year}, {class: 'time-box'} %>
            </div>
            <div>
                <%= f.label :"試合時間を選択" %></br>
                <%= f.time_select :match_start,{include_blank: true, start_hour: 8, end_hour: 20, minute_step: 15}, {class: 'time-box'} %>
            </div>
            <div>
                <%= f.label :"試合場所を選択" %></br>
                <%= f.select :area, [["神奈川県", "神奈川県"], ["東京都", "東京都"]], placeholder: "神奈川県" %>
            </div>
            <div>
                <%= f.text_field :place, placeholder: "グランド名などの詳細・・・"  %>
            </div>

            <div>
                <%= f.label :"カテゴリ又はレベルなどを入力" %></br>
                <%= f.text_field :category %>
            </div>

            <div class = "game_contents a" >
                <%= f.label :"コメントを入力" %>
            </div>
            <div class = "game_contents b" >
                <%= f.text_area :game_contents %>
            </div>

            <%= f.hidden_field :confirming %>

        </div>
        <%= f.submit '確認画面へ'%>
    <% end %>
<% else %>
    <%= form_for @event, multipart:true, local: true  do |f|%>
        <div>
            <div>
                <%= f.label :"試合種別" %>
                <%= @event.sports %>
            </div>
            <div>
                <%= f.label :"試合種別" %>
                <%= @event.match %>
            </div>
            <div>
                <%= f.label :"募集タイトル" %>
                <%= @event.title %>
            </div>
            <div>
                <%= f.label :"希望試合日" %>
                <%= @event.start_time.strftime("%Y年%m月%d日") %>
            </div>
            <div>
                <%= f.label :"希望試合時間" %>
                <%= @event.match_start.strftime("%H:%M") %>
            </div>
            <div>
                <%= f.label :"希望試合エリア" %>
                <%= @event.area %>
            </div>
            <div>
                <%= f.label :"試合場所" %>
                 <%= @event.place %>
            </div>
            <div>
                <%= f.label :"カテゴリ又はレベル" %>
                <%= @event.category %>
            </div>
            <div class = "game_contents a" >
                <%= f.label :"コメント" %>
            </div>
            <div class = "game_contents b" >
                <%= @event.game_contents %>
            </div>

            <%= f.hidden_field :title %>
            <%= f.hidden_field :start_time %>
            <%= f.hidden_field :match_start %>
            <%= f.hidden_field :area %>
            <%= f.hidden_field :place %>
            <%= f.hidden_field :match %>
            <%= f.hidden_field :sports %>
            <%= f.hidden_field :category %>
            <%= f.hidden_field :game_contents %>
            <%= f.hidden_field :confirming %>

        </div>
        <%= f.submit '募集する'%> 
    <% end %>
    <%= link_to "入力画面に戻る", posts_back_path %>
<% end %>

Desktop/OnField_master/app/views/posts/show.html.erb
      <artile id="recruitment-list">
      <section class="section-display-area">
<div class="table-title-box">
<p><%= @date_time.strftime("%Y年%m月%d日") %>の募集一覧</p>
</div>

<% if @events != [] %>

<div class="search-form">
  <%= form_with url: posts_show_search_path, method: :get, local: true do |f| %>
    <%= f.hidden_field :time, value: @date_time %>
    <%= f.hidden_field :events, value: @events %>    
    <%= f.text_field :keyword, value: @keyword %>
    <%= f.submit "検索" %>
  <% end %>  
</div>

<div class="recruitment-list-table-box">
<table>
<thead>
<tr>
  <th class="contents", width="40%">募集内容</th>
  <th class="place", width="20%">場所</th>
  <th class="time", width="20%">時間</th>
  <th class="name", width="20%">名前</th> <!-- カレンダーから遷移した場合は名前、プロフィールから遷移した場合は日にち -->
</tr>
</thead>
<tbody>
    <% @events.each do |event| %>
        <tr>
        <td width="40%"><%= link_to event.title, {controller: :posts,action: :details,id: event.id} %></td>
        <td><%= link_to event.place, {controller: :posts,action: :details,id: event.id} %></td>
        <td><%= link_to event.match_start.strftime("%H:%M~"), {controller: :posts,action: :details,id: event.id} %></td>
        <td><%= link_to event.contributor, {controller: :posts,action: :details,id: event.id} %></td>
        </tr>
    <% end %>
    <%= paginate @events %>
<% else %>
    <div class="no-title" >
    <p>募集はありません。</p>
    <%= link_to '試合を募集する', new_post_path %></br>
    <%= link_to '募集一覧へ戻る', :back %></br>
    <%= link_to "トップページへ戻る", root_path %>
    </div>
<% end %>
</table>
</div>

<div class= "new-recruitment">
<span style="text-decoration: underline"><%= link_to '試合を募集する', new_post_path %><span></br>
<span style="text-decoration: underline"><%= link_to '戻る', :back %></span></br>
</div>
</section>
</artile>